#ifndef LOKA_SMIRK_BENCH_PLAIN_EDITOR_SCENARIO_HPP
#define LOKA_SMIRK_BENCH_PLAIN_EDITOR_SCENARIO_HPP
#include "SmirkBenchPlainEditorNode.hpp"
#include "ToolboxScenePlatformController.hpp"
#include "SmirkBenchAttributedScenario.hpp"
#include "ScenarioCellTable.hpp"
#include "../toolbox/ToolboxTextEditorAccess.hpp"
namespace loka
{
  namespace scenario_tests
  {
    /** Toolbox-only staged cell. macOS and Win32 refuse TextEditor until PR 3.
        LokaTest.cfg is generated by run-scenario.sh; golden bundle approval is separate. */
    inline ScenarioCellTable SmirkBenchToolboxCells()
    {
      static const char *const cells[] = {"startup",
                                          "surface-ticks",
                                          "add-face",
                                          "retained-text-rebind",
                                          "attributed-editor-line",
                                          "text-editor-plain"};
      return ScenarioCellTable(cells, sizeof(cells) / sizeof(cells[0]));
    }
    inline ScenarioAdvance AdvanceSmirkBenchPlainEditor(long tick,
                                                        app::scene::Scene *scene,
                                                        ToolboxScenePlatformController &controller,
                                                        dsl::testing::ScenarioAuditSink &audit,
                                                        dsl::SnapRecord &out)
    {
      if (tick < 2)
        return SCENARIO_ADVANCE_PENDING;
      app::scene::Node *node = 0;
      dsl::FlowError error;
      bool ok = scene
                && dsl::testing::LookupNodeById<app::scene::Node>(scene, "SmirkBench.PlainEditor", node, error)
                       == dsl::FLOW_STEP_SUCCEEDED;
      app::TextEditorNode *editor =
          ok && node && node->nodeTypeKey() == app::scene::NodeTypeToken<app::TextEditorNode>()
              ? static_cast<app::TextEditorNode *>(node)
              : 0;
      ToolboxTextEditorContext *context = editor ? static_cast<ToolboxTextEditorContext *>(editor->getContext()) : 0;
      ok = context && testing::ToolboxTextEditorAccess::status(*context) == app::EDITOR_OK;
      const char *step = "capture";
      if (ok)
      {
        TEHandle te = testing::ToolboxTextEditorAccess::te(*context);
        if (tick == 2)
        {
          Point point;
          point.h = (**te).viewRect.left + 1;
          point.v = (**te).viewRect.top + (**te).lineHeight + 1;
          ok = controller.handleMouseDown(point)
               && editor->props.cursor_.state()->get().line == editor->props.lines_->at(1).id;
          step = "click-line-2";
        }
        else if (tick == 3)
        {
          ok = controller.handleKeyDown('x');
          step = "type-x";
        }
        else if (tick == 4)
        {
          ok = controller.handleKeyDown('\r') && editor->props.lines_->size() == 4;
          step = "split-3-to-4";
        }
        else if (tick == 5)
        {
          ok = controller.handleKeyDown('y');
          step = "type-y";
        }
        else if (tick == 6)
        {
          ok = controller.handleKeyDown(28);
          step = "left-to-start";
        }
        else if (tick == 7)
        {
          ok = controller.handleKeyDown('\b') && editor->props.lines_->size() == 3;
          step = "join-4-to-3";
        }
        else if (tick == 8)
        {
          // Length preflight deliberately precedes dereferencing this oversized payload.
          ok = context->paste("", app::TextEditorProps::kMaxBytes + 1) == app::EDITOR_CAPACITY
               && testing::ToolboxTextEditorAccess::restores(*context) == 1;
          step = "paste-cap-refused";
        }
        else
        {
          // Capture with no focused TextEdit caret blinking between settle samples.
          Point outside = {0, 0};
          (void)controller.handleMouseDown(outside);
          ok = !(**te).active;
        }
        if (ok)
          ok = audit.recordStep(dsl::testing::ScenarioStepTerminal(
              static_cast<int>(tick), step, tick, tick, dsl::FLOW_STEP_SUCCEEDED, error));
      }
      if (ok && tick < 9)
        return SCENARIO_ADVANCE_PENDING;
      std::string projection;
      if (ok)
        ok = editor->document.project(projection) == app::EDITOR_OK && projection == "first\rxysecond\rthird";
      out = SmirkBenchEditorRecord("text-editor-plain", tick, ok);
      if (ok)
      {
        out.set("line2", "xysecond");
        out.set("line_counts", "3->4->3");
        out.set("cap", "refused");
        out.setInt("restores", testing::ToolboxTextEditorAccess::restores(*context));
      }
      return SCENARIO_ADVANCE_DRIVER_COMPLETION_READY;
    }
  } // namespace scenario_tests
} // namespace loka
#endif
