#ifndef LOKA_APPLICATION_FILE_TESTS_HPP
#define LOKA_APPLICATION_FILE_TESTS_HPP

void testApplicationFileCompositionKeepsExplicitBase();
void testApplicationRelativePredicateEnforcesSingleSegment();
void testNullApplicationFileUsesOnlyInjectedDirectory();
void testGenericFlushWriteRefusesClosedDurabilityDoor();

#endif // LOKA_APPLICATION_FILE_TESTS_HPP
