#ifndef LOKA_TESTS_BOUNDARY_OBSERVED_STATE_TRACKER_TESTS_HPP
#define LOKA_TESTS_BOUNDARY_OBSERVED_STATE_TRACKER_TESTS_HPP

void testObservedStateDoesNotJoinChildBoundaryTracker();
void testObservedStateGuardSharesRegistrationTokenAndUnbindsLate();

#endif // LOKA_TESTS_BOUNDARY_OBSERVED_STATE_TRACKER_TESTS_HPP
