#ifndef LOKA_BOUNDARY_ARENA_TESTS_HPP
#define LOKA_BOUNDARY_ARENA_TESTS_HPP

void testBoundaryArenaContracts();
void testNodeArenaRetiredGenerationContracts();
void testStateArenaSlabsCrossAllocationGate();
void testNodeArenaSlabCrossesAllocationGate();
void testHeapNodeCrossesAllocationGate();
void testGateAllocatedNodeRejectsUnauthorizedDestruction();
void testComposeAllocationWhiteFlagDefersFullRebuildToNextExternalTick();
void testHeapFallbackWhiteFlagFailsBoundaryCompose();
void testSceneRootAllocationRefusalArmsWhiteFlagAndHealsOnRefresh();
void testLocalRebuildNodeRefusalDefersFullRebuildToNextExternalTick();
void testLocalRebuildLaterChildRefusalDoesNotLeakEarlierChild();
void testNestedLocalRebuildChildRefusalDefersFullRebuildToNextExternalTick();
void testNestedConditionalSeatInContextlessMaterialization_Probe();
void testNestedConditionalSeatDefersProjectionAndRecoversThroughRootBoundaryWrapper();
void testRootAttachAllocationRefusalKeepsWhiteFlagArmedForRetry();
void testBoundarySectionKeyIdentityAndTwoPhaseStateRetirement();
void testBoundarySectionRetainedKeyReconcilesReplacedChild();
void testBoundarySectionRetainedKeyAppliesChangedChildPropsInPlace();
void testBoundarySectionRejectsMissingAndDuplicateSiblingKeys();
void testBoundarySectionAllocationFailureKeepsBoundaryRefusalAtomic();
void testBoundarySectionGridUsesEnclosingStateArenaEconomically();

#endif // LOKA_BOUNDARY_ARENA_TESTS_HPP
