#ifndef LOKA_DEFINITION_CLONE_TESTS_HPP
#define LOKA_DEFINITION_CLONE_TESTS_HPP

void testConditionalDefinitionCloneOwnership();
void testNestableDefinitionCloneRejectsNullChildClone();
void testNestableDefinitionAssignmentRejectsNullChildClone();

#endif // LOKA_DEFINITION_CLONE_TESTS_HPP
