#ifndef LOKA_DEFINITION_CLONE_TESTS_HPP
#define LOKA_DEFINITION_CLONE_TESTS_HPP

void testConditionalDefinitionCloneOwnership();
void testOwnedDefOwnership();
void testNestableDefinitionCloneReturnsNullOnOomChildClone();
void testNestableDefinitionAssignmentPreservesStableChildOnOomClone();
void testCompositionSnapshotClearsStaleRootOnOomClone();
void testNodeCompositionSkipsOomClones();
void testWindowPropsAssignmentPreservesOwnedSceneOnOomClone();
void testWindowDefinitionCreateReturnsNullOnOomRootClone();
void testWindowDefinitionCreateTransfersSingleRootClone();
void testMenuControllerPreservesDefaultMenuBarOnOomClone();
void testMenuControllerPreservesRefreshedMenuBarOnOomClone();
void testMenuControllerRequeuesDirtyMenusAfterOomClone();
void testMenuControllerSchedulesRetryAfterDirectRefreshFailure();

#endif // LOKA_DEFINITION_CLONE_TESTS_HPP
