#ifndef LOKA_DEFINITION_CLONE_TESTS_HPP
#define LOKA_DEFINITION_CLONE_TESTS_HPP

void testConditionalDefinitionCloneOwnership();
void testNestableDefinitionCloneReturnsNullOnOomChildClone();
void testNestableDefinitionAssignmentPreservesStableChildOnOomClone();
void testCompositionSnapshotClearsStaleRootOnOomClone();
void testWindowPropsAssignmentPreservesOwnedSceneOnOomClone();
void testWindowDefinitionCreateReturnsNullOnOomRootClone();
void testWindowDefinitionCreateTransfersSingleRootClone();

#endif // LOKA_DEFINITION_CLONE_TESTS_HPP
