#ifndef LOKA_TESTS_FLOPPY_BIRD_SCENARIO_TESTS_HPP
#define LOKA_TESTS_FLOPPY_BIRD_SCENARIO_TESTS_HPP

void testFloppyBirdFixedStepFlapsDriveSeededGame();
void testFloppyBirdFixedStepFlapsHoldFinalSceneAndMatchAudit();
void testFloppyBirdDifferentSeedRefusesFixedCheckpointAudit();
void testFloppyBirdStandaloneFlowWritesExpectedAudit();
void testFloppyBirdStandaloneMountRefusalFailsClosed();

#endif // LOKA_TESTS_FLOPPY_BIRD_SCENARIO_TESTS_HPP
