#ifndef LOKA_FOCUS_PUBLISHER_TESTS_HPP
#define LOKA_FOCUS_PUBLISHER_TESTS_HPP
void testFocusSameFact();
void testFocusAcrossFacts();
void testFocusUnpublished();
void testFocusReplacement();
void testFocusDetach();
void testFocusObserverRetiresTarget();
void testFocusSameTarget();
void testFocusTwoWindows();
void testFocusQuery();
void testFocusTextEditor();
void testFocusValues();
void testFocusCoalescedReattach();
void testFocusReentrantCompletion();
void testFocusAdmission();
void testFocusInvalidBindingReplacement();
void testFocusNullRefusesSceneless();
void testFocusSourceLifetime();
void testFocusLogicalEligibility();
void testFocusSceneRun();
void testFocusPublicationGate();
void testFocusSceneReplacement();
void testFocusReplaceSameKey();
void testFocusAudit();
void testFocusWindowGates();
void testFocusAppFlushGate();
void testFocusObserverRebindsTarget();
void testFocusObserverCutsEdge();
void testFocusAppReenumerates();
void testFocusNullCompletion();
void testFocusForeignRow();
#endif
