#ifndef LOKA_TESTS_HELLO_WORLD_SCENARIO_TESTS_HPP
#define LOKA_TESTS_HELLO_WORLD_SCENARIO_TESTS_HPP

void testHelloWorldToggleActionProbeDrivesOwnerCommands();
void testHelloWorldToggleActionProbeHoldsFinalScene();
void testHelloWorldClassicVehiclePresentationUsesExampleDeclaration();
void testHelloWorldStandaloneMenuMatchesExample();
void testHelloWorldStandaloneMountRefusalFailsClosed();

#endif // LOKA_TESTS_HELLO_WORLD_SCENARIO_TESTS_HPP
