#ifndef LOKA_TESTS_HELLO_WORLD_SCENARIO_TESTS_HPP
#define LOKA_TESTS_HELLO_WORLD_SCENARIO_TESTS_HPP

void testHelloWorldToggleActionProbeDrivesOwnerCommands();
void testHelloWorldToggleActionProbeHoldsFinalScene();

#endif // LOKA_TESTS_HELLO_WORLD_SCENARIO_TESTS_HPP
