#ifndef LOKA_TESTS_LIFECYCLE_DETACH_TESTS_HPP
#define LOKA_TESTS_LIFECYCLE_DETACH_TESTS_HPP

void testSceneUnmountNotifiesPlainNodeContextDetached();
void testSceneUpdateAttachedFalseNotifiesPlainNodeContextDetachedOnce();
void testSceneTeardownNotifiesBoundaryInternalNodeContextDetachedOnce();
void testRootDetachChildWalkRetainsBoundaryStateOwner();
void testConditionalBranchSwapDestroysRetiredArenaNodeOnNextTrackerRun();
void testRootReplacementDestroysRetiredArenaNodeOnNextTrackerRun();
void testRetiringNativeContextUnbindsBeforeNodeOwnedStateReclaim();
void testRetiredGenerationSubsumesQueuedArenaSubtreeExactlyOnce();
void testSceneDestructionUnbindsNativeContextBeforeNodeOwnedStateReclaim();
void testSceneTeardownDrainsNonEmptyRetiredArenaSubtreeExactlyOnce();
void testBoundaryTeardownDrainsPendingRetiredGenerationExactlyOnce();
void testConditionalBranchSwapDestroysRetiredArenaSubtreeChildrenFirst();
void testRetiredArenaParentDestroysHeapChildExactlyOnceAtDrain();
void testConditionalBranchSwapBackDestroysRetiredHeapNodeOnNextTrackerRun();
void testPendingChildBoundaryUpdateSurvivesHeapSubtreeReplacement();
void testRetiredHeapParentDestroysArenaChildExactlyOnceAtDrain();
void testRetiredGenerationSubsumesQueuedHeapSubtreeExactlyOnce();
void testRetiredSubtreeDestroysNestedBoundaryArenaExactlyOnce();
void testRetiredBoundaryOwnedStateMutationIsQuiescent();
void testRetiredBoundaryIsQuiescentBeforeNextTrackerRun();
void testDirectRootBoundaryReRegistersObservedStateAcrossReattach();
void testSceneTeardownReleasesBothConditionalBranchContextsOnce();
void testConditionalConditionWriteDuringDetachDoesNotMaterializeBranch();

#endif // LOKA_TESTS_LIFECYCLE_DETACH_TESTS_HPP
