#ifndef LOKA_TESTS_LIFECYCLE_DETACH_TESTS_HPP
#define LOKA_TESTS_LIFECYCLE_DETACH_TESTS_HPP

void testSceneUnmountNotifiesPlainNodeContextDetached();
void testSceneUpdateAttachedFalseNotifiesPlainNodeContextDetachedOnce();
void testBoundaryLocalRebuildNotifiesCompositionDetachedOnce();
void testSceneTeardownNotifiesBoundaryInternalNodeContextDetachedOnce();
void testRootDetachChildWalkRetainsBoundaryStateOwner();
void testConditionalUnbindsBeforeReclaim();
void testConditionalBranchSwapNotifiesContextsAcrossRetainedDetach();
void testConditionalBranchSwapNotifiesNestedContextsAcrossRetainedDetach();
void testConditionalBranchSwapDestroysRetiredArenaNodeOnNextTrackerRun();
void testRootReplacementDestroysRetiredArenaNodeOnNextTrackerRun();
void testRetiringNativeContextUnbindsBeforeNodeOwnedStateReclaim();
void testRootUpdateFallbackDestroysRetiredArenaNodeOnNextTrackerRun();
void testRootUpdateFallbackReservesFreshArenaGeneration();
void testRetiredGenerationSubsumesQueuedArenaSubtreeExactlyOnce();
void testRootUpdateFallbackReleasesNativeContextBeforeNodeOwnedStateReclaim();
void testSceneDestructionUnbindsNativeContextBeforeNodeOwnedStateReclaim();
void testSceneTeardownDrainsNonEmptyRetiredArenaSubtreeExactlyOnce();
void testSceneTeardownDrainsPendingRetiredGenerationExactlyOnce();
void testConditionalBranchSwapDestroysRetiredArenaSubtreeChildrenFirst();
void testRetiredArenaParentDestroysHeapChildExactlyOnceAtDrain();
void testConditionalBranchSwapBackDestroysRetiredHeapNodeOnNextTrackerRun();
void testPendingChildBoundaryUpdateSurvivesHeapSubtreeReplacement();
void testRetiredHeapParentDestroysArenaChildExactlyOnceAtDrain();
void testRetiredGenerationSubsumesQueuedHeapSubtreeExactlyOnce();
void testRetiredSubtreeDestroysNestedBoundaryArenaExactlyOnce();
void testRetiredBoundaryOwnedStateMutationIsQuiescent();
void testRetiredBoundaryIsQuiescentBeforeNextTrackerRun();
void testSceneTeardownReleasesBothConditionalBranchContextsOnce();

#endif // LOKA_TESTS_LIFECYCLE_DETACH_TESTS_HPP
