#ifndef LOKA_TESTS_LIFECYCLE_DETACH_TESTS_HPP
#define LOKA_TESTS_LIFECYCLE_DETACH_TESTS_HPP

void testSceneUnmountNotifiesPlainNodeContextDetached();
void testSceneUpdateAttachedFalseNotifiesPlainNodeContextDetachedOnce();
void testBoundaryLocalRebuildNotifiesCompositionDetachedOnce();
void testSceneTeardownNotifiesBoundaryInternalNodeContextDetachedOnce();
void testConditionalUnbindsBeforeReclaim();
void testConditionalBranchSwapFiresContextHooksOncePerLifetime();
void testSceneTeardownReleasesBothConditionalBranchContextsOnce();

#endif // LOKA_TESTS_LIFECYCLE_DETACH_TESTS_HPP
