#ifndef LOKA_TESTS_LRPKGOLDENBYTESTESTS_HPP
#define LOKA_TESTS_LRPKGOLDENBYTESTESTS_HPP

void testLrpkWireFormatMatchesAnIndependentlyAssembledPackage();
void testLrpkGoldenBytesReadTheSameThroughEveryTransport();

#endif // LOKA_TESTS_LRPKGOLDENBYTESTESTS_HPP
