#ifndef LOKA_MAC_APP_LOCATION_TESTS_HPP
#define LOKA_MAC_APP_LOCATION_TESTS_HPP

void testMacApplicationItemNamesResourceDirectory();
void testMacApplicationSidecarNamesBundleParent();
void testMacApplicationSidecarDeclinesWhenParentReportsReadOnly();

#endif // LOKA_MAC_APP_LOCATION_TESTS_HPP
