#ifndef LOKA_TESTS_MAC_MENU_PROJECTION_TESTS_HPP
#define LOKA_TESTS_MAC_MENU_PROJECTION_TESTS_HPP

void testMacMenuProjectionDetachesMainMenuBeforeReleasingTarget();

void testMacMenuAttachmentProjectsOnceForEqualBar();
void testMacMenuDoorSkipsProjectionDuringTracking();
void testMacMenuAttachmentDisconnectStripsTargetAndAction();
void testMacSceneDetachReleasesMenu();
void testMacAppShutdownReleasesMenuBeforeAttachmentDestruction();
void testMacMenuAttachmentCloneRefusalClearsBaseline();
void testMacMenuAttachmentDispatchMayDisconnect();

void testMacMenuTitleFollowsState();
void testMacMenuSubmenuTitleFollowsState();
void testMacMenuTitleStateUnbindsOnRelease();

#endif // LOKA_TESTS_MAC_MENU_PROJECTION_TESTS_HPP
