#ifndef LOKA_MAC_SCENE_PLATFORM_TESTS_HPP
#define LOKA_MAC_SCENE_PLATFORM_TESTS_HPP

void testMacScenePlatformRelayoutRequest();
void testMacScenePlatformIgnoresNonLayoutDirtyRequest();
void testMacScenePlatformRelayoutReusesControlContexts();

#endif // LOKA_MAC_SCENE_PLATFORM_TESTS_HPP
