#ifndef LOKA_MAC_SCENE_PLATFORM_TESTS_HPP
#define LOKA_MAC_SCENE_PLATFORM_TESTS_HPP

void testMacScenePlatformRelayoutRequest();
void testMacScenePlatformIgnoresNonLayoutDirtyRequest();
void testMacScenePlatformDynamicPropsAndLayoutReuseContexts();
void testMacScenePlatformRelayoutReusesControlContexts();
void testMacScenePlatformRelayoutReusesCellAndTextContexts();
void testMacScenePlatformFullRebuildFlagControlsContextReuse();
void testMacScenePlatformChildRebuildCleansUpOldContexts();

#endif // LOKA_MAC_SCENE_PLATFORM_TESTS_HPP
