#ifndef LOKA_TESTS_MENU_CHECKED_TESTS_HPP
#define LOKA_TESTS_MENU_CHECKED_TESTS_HPP

void testMenuItemCheckedAttrProjectsValueAndState();
void testSimpleViewerDisplayModeUpdatesRetainedImageViewProps();

#endif // LOKA_TESTS_MENU_CHECKED_TESTS_HPP
