#ifndef LOKA_MENU_COMPLETION_TESTS_HPP
#define LOKA_MENU_COMPLETION_TESTS_HPP
void testMenuProjectedAtCompletionNotOnActivation();
void testLastWindowCloseProjectsDefaultInSameTurn();
void testMenuSourceMergesDefaultAndActiveScene();
void testMergeMenuBarsReplacesInPlaceAndAppendsInOrder();
void testMenuMergeCloneRefusalSkipsRowKeepsNextCompletion();
void testInactiveWindowCloseKeepsActiveBar();
void testTwoAdmissionsReofferSameSource();
void testBootstrapProjectsOnce();
void testDefaultBarComposedOnceAtBootstrap();
void testDefaultBarBootstrapCloneRefusalLeavesNoDefault();
void testDefaultBarReplacementCloneRefusalPreservesInstalledValue();
#endif
