#ifndef LOKA_NODE_MATCH_TESTS_HPP
#define LOKA_NODE_MATCH_TESTS_HPP

void testNodeMatchSelectsFirstDeclaredValueArm();
void testNodeMatchPredicatePrecedesValueArmAndRunsOncePerVisit();
void testNodeMatchEmptySeatRematerializes();
void testNodeMatchOtherwiseIsTheLastArm();
void testNodeMatchRestoresThreeIndependentArmStates();
void testNodeMatchDestroyOnDetachIsPerArm();
void testNodeMatchCapacityRefusesOverflow();

void testKeyedRedeclaresCurrentMembersOnceAndReclaimsOnDrain();
void testKeyedRefusedDeclarationKeepsLiveBranchAndRetriesCurrentKey();
void testKeyedDeclarationUsesGenerationOwnerInsideSectionOnMountAndUpdate();
void testKeyedOwnsFreshNestedSeatPlansAcrossReplacement();

void testKeyedFailedOuterCandidatePublishesNoNestedObservations();

void testKeyedDirectSeatRootSurvivesInnerSwitchAndDrain();

void testKeyedRemovesOnlyUnsharedOutgoingObservations();

void testKeyedRetiresNestedParkedScopeBeforeDeclarationReset();

void testKeyedComposeWriteRetainsSeatDirtyClassification();

void testKeyedOutgoingSeatSourceRemainsObservedByOrdinaryNode();

void testPlainRootMatchUpdateComposesOnceAndWalksChildrenOnce();
void testNestedStdBoundaryUpdateWalksChildrenOnce();
void testDoublyNestedStdBoundaryUpdateWalksChildrenOnce();
void testDirectRootKeyedReplacementAttachesBeforeUpdatingLeaf();
void testDirectRootKeyedNestedBoundaryAttachesLeafOnce();
void testPlainRootChildDirtWithoutSeatOnlyWalks();

#endif // LOKA_NODE_MATCH_TESTS_HPP
