#ifndef LOKA_TESTS_NULL_LAYOUT_TESTS_HPP
#define LOKA_TESTS_NULL_LAYOUT_TESTS_HPP

void testFallbackControlMetricsContract();
void testNullLayoutRowProducesFixedChildGeometry();
void testNullLayoutColumnProducesFixedChildGeometry();
void testNullLayoutFragmentAdvancesAcrossChildren();
void testNullLayoutBoxProducesFixedChildGeometry();
void testNullLayoutGridProducesFixedChildGeometry();
void testNullLayoutZStackProducesFixedChildGeometry();
void testNullLayoutNestedBoxAndRowProduceFixedChildGeometry();
void testNullLayoutOnChangeUsesRegisteredTraversal();

#endif // LOKA_TESTS_NULL_LAYOUT_TESTS_HPP
