#ifndef LOKA_TESTS_NULL_PLATFORM_CONTRACT_TESTS_HPP
#define LOKA_TESTS_NULL_PLATFORM_CONTRACT_TESTS_HPP

void testNullPlatformContract_A1_contextDestructorRunsTeardownSequence();
void testNullPlatformContract_A2_retainedDetachRunsNoTeardown();
void testNullPlatformContract_A3_intakeConsistencyFailureLeaksWithoutPooling();
void testNullPlatformContract_B1_attachShowsControl();
void testNullPlatformContract_B2_retainedDetachHidesAndKeepsRow();
void testNullPlatformContract_B3_reattachKeepsHandleIdentity();
void testNullPlatformContract_B4_retireRemovesLedgerRow();
void testNullPlatformContract_B5_hiddenAncestorSwapIsSilent();
void testNullPlatformContract_C2_hintControlsFlushPolicy();
void testNullPlatformContract_C3_hintChangesReachNextObservation();
void testNullPlatformContract_D1_exactMatchBucketsStaySeparated();
void testNullPlatformContract_D2_churnProducesPoolHits();
void testNullPlatformContract_D3_depthCapRefusalCountsEvict();
void testNullPlatformContract_D4_controllerDrainPrecedesWindowDispose();
void testNullPlatformContract_E1_reclaimOnlyFlushIsSilent();
void testNullPlatformContract_E2_disposeOccursOnlyAtSafePoints();
void testNullPlatformContract_E3_parkedBranchRetiresAtTheDoorNotAtReclaim();
void testNullPlatformContract_H1_conditionalSeatSurvivesUnrelatedRecompose();
void testNullPlatformContract_H2_parkedDraftBranchSurvivesUnrelatedRecompose();
void testConditionalSeatRepointsBranchDefinitionsAfterUnrelatedRecompose();
void testNullPlatformContract_H3_conditionFlipIsReflectedAtNextScheduledApply();
void testNullPlatformContract_H4_retiringBoundaryReportsEveryParkedBranchRetiredInSameTick();
void testNullPlatformContract_H5_taggedSeatAmongSiblingsSurvivesUnrelatedRecompose();
void testNullPlatformContract_H6_activeBranchContentIsFreshAfterRecompose();
void testNullPlatformContract_H7_reenteredBranchContentIsFreshAfterRecompose();
void testNullPlatformContract_F1_retiredQueueIsEmptyAfterFlush();
void testNullPlatformContract_F2_createdHandlesAreDisposedAtTeardown();
void testNullPlatformContract_G4_retireBeforeContextAttachIsSilent();
void testNullWindowScenePathMountsAndTearsDownBeforeControllerDelete();
void testNullPlatformContract_G6_materializedChildIsVisibleInSameRun();

#endif // LOKA_TESTS_NULL_PLATFORM_CONTRACT_TESTS_HPP
