#ifndef LOKA_TESTS_NULL_TEXT_LAYOUT_TESTS_HPP
#define LOKA_TESTS_NULL_TEXT_LAYOUT_TESTS_HPP

void testNullTextLayoutWordAndCharacterWrapProduceDifferentGeometry();
void testNullTextLayoutTruncationModesProduceDifferentWidths();
void testNullTextLayoutHonorsExplicitBreaksAndForceBreaksLongWords();
void testNullTextLayoutUsesFixedAdvancePerCodePoint();

#endif // LOKA_TESTS_NULL_TEXT_LAYOUT_TESTS_HPP
