#ifndef LOKA_TESTS_PACKMANIFESTTESTS_HPP
#define LOKA_TESTS_PACKMANIFESTTESTS_HPP

void testPackManifestParsesRecordsAndRefusesMalformedLines();
void testPackManifestStampFollowsTheIdSpaceNotTheListing();
void testPackageRequirementsCheckEveryScrapbookExpectation();
void testPackageRequirementsUnreadableFileIsAHardError();

#endif // LOKA_TESTS_PACKMANIFESTTESTS_HPP
