#ifndef LOKA_TESTS_PARTIAL_TREE_PUBLICATION_TESTS_HPP
#define LOKA_TESTS_PARTIAL_TREE_PUBLICATION_TESTS_HPP
void testPartialTree629();
void testPartialTree144();
void testPartialTree144PlainRoot();
void testPartialTree144NestedBoundary();
void testPartialTreeDiscardWithdrawsBindings();
void testPartialTreeDrainOnlyDoesNotRetry();
void testExpectedRedPartialTreeAttachRefusal144();
void testPartialTree100Children();
void testPartialTreeHealthyControl();
void testPartialTreeNullRootSwitchRecovery();
void testPartialTreeConditionalSectionRoundTrip271();
void testPartialTreeFirstFactoryRefusal();
void testPartialTreeMiddleFactoryRefusal();
void testPartialTreeLastFactoryRefusal();
void testPartialTreePlainRootFactoryRefusal();
void testPartialTreeInitialRootCloneRefusal();
void testPartialTreeInitialChildCloneRefusal();
void testPartialTreeEmptyDeclarationComposesOnce();
void testPartialTreePlainRootCloneRefusal();
void testPartialTreeInitialTaggedCopyRefusal();
void testPartialTreeNestedReconcileGrowsSeatLedger925();
void testPartialTreeNestedReconcileRefusalAfterLedgerGrowth925();
#endif
