#ifndef LOKA_TESTS_PARTIAL_TREE_PUBLICATION_TESTS_HPP
#define LOKA_TESTS_PARTIAL_TREE_PUBLICATION_TESTS_HPP
void testPartialTree629();
void testPartialTree144();
void testPartialTree144PlainRoot();
void testPartialTree144NestedBoundary();
void testPartialTreeDiscardWithdrawsBindings();
void testPartialTreeDrainOnlyDoesNotRetry();
void testExpectedRedPartialTreeAttachRefusal144();
void testPartialTree100Children();
void testPartialTreeHealthyControl();
void testPartialTreeNullRootSwitchRecovery();
void testPartialTreeConditionalSectionRoundTrip271();
void testPartialTreeFirstFactoryRefusal();
void testPartialTreeMiddleFactoryRefusal();
void testPartialTreeLastFactoryRefusal();
void testPartialTreePlainRootFactoryRefusal();
void testPartialTreeInitialRootCloneRefusal();
void testPartialTreeInitialChildCloneRefusal();
void testPartialTreeEmptyDeclarationComposesOnce();
void testPartialTreePlainRootCloneRefusal();
void testPartialTreeInitialTaggedCopyRefusal();
void testPartialReplacementLazyScopeStaging();
void testPartialReplacementConditionFlip();
void testPartialReplacementDiscardWithdrawsBindings();
void testPartialReplacementUntaggedStateAndReclaim();
void testPartialReplacementStagingOwnership();
void testPartialReplacementCommitsNestedObservations();
void testPartialReplacementDiscardSkipsDetach();
void testPartialReplacementStagingAllocationRefusal();
void testPartialReplacementDeclarationDiscardSkipsDetach();
void testPartialReplacementAdmittedDiscardSkipsDetach();
void testPartialReplacementConditionalCommitsNestedObservations();
void testPartialReplacementShowCommitsNestedObservations();
void testPartialReplacementLocalRebuildCommitsNestedObservations();
void testBranchSeatCaptureOverLiveLedgerAborts();

#endif
