#ifndef LOKA_PHASE_GUARD_TESTS_HPP
#define LOKA_PHASE_GUARD_TESTS_HPP

void testDetachClearsQueuedBoundaryUpdate();
void testSceneReplacementRequestedDuringApplyIsAppliedAtNextAdmission();

void testDirectSceneRunDefersReplacementUntilAppAdmission();

void testCrossWindowCallbackDefersReplacementUntilNextAppAdmission();

void testDetachRequestedDuringApplyIsAppliedAtNextAdmission();

void testRearmRequestedTwiceDuringApplyRenewsOnceAtNextAdmission();
void testDetachAndRearmRequestsUseLastRequestAtAdmission();
void testDirectSceneRunDefersDetachUntilNextAppAdmission();

void testRequestFromDetachObserverWaitsForFollowingAdmission();
void testSeatRequestAppliesToReplacementInstalledAtAdmission();
void testVisibilityHideDuringApplyWaitsForNextAdmission();
void testVisibilityToggleDuringApplyUsesFinalValue();
#endif // LOKA_PHASE_GUARD_TESTS_HPP
