#ifndef LOKA_PHASE_GUARD_TESTS_HPP
#define LOKA_PHASE_GUARD_TESTS_HPP

void testDetachClearsQueuedBoundaryUpdate();
void testSceneReplacementRequestedDuringApplyIsAppliedAtNextAdmission();

void testDirectSceneRunDefersReplacementUntilAppAdmission();

void testCrossWindowCallbackDefersReplacementUntilNextAppAdmission();

#endif // LOKA_PHASE_GUARD_TESTS_HPP
