#ifndef LOKA_TESTS_ROW_WIDTH_CONSULTATION_TESTS_HPP
#define LOKA_TESTS_ROW_WIDTH_CONSULTATION_TESTS_HPP

void testRowFixedBoxWidthLeavesOnlyRemainingSeatForText();
void testRowWidthOnlyBoxLeavesOnlyRemainingSeatForText();
void testRowEmptyFragmentConsumesNeitherSeatNorGap();
void testRowMaterializedDialogConsumesNeitherSeatNorGap();
void testRowMaterializedDialogDoesNotRaiseAlignedRowHeight();
void testRowBranchArmSwitchRelayoutsWidthConsultation();
void testRowWidthOnlyBranchArmForwardsWidthClaim();
void testRowHeightOnlyBoxKeepsFlexSeat();
void testRowWidthOnlyBoxUsesRowHeight();
void testColumnWidthOnlyBoxKeepsFullAvailableWidth();
void testRowOversizedFixedBoxKeepsDeclaredSeatForSibling();
void testRowZeroWidthRowKeepsFixedSeatLiveAndGapped();
void testRowWidthHeuristicForwardsOnlySingleFragmentClaims();

void testRowNaturalWidthConsultation();
void testRowSharedWidthNeverQueriesSource();

void testNullNaturalWidthDeclinesUnrepresentableWidth();

#endif // LOKA_TESTS_ROW_WIDTH_CONSULTATION_TESTS_HPP
