#ifndef LOKA_SCENE_OWNERSHIP_TESTS_HPP
#define LOKA_SCENE_OWNERSHIP_TESTS_HPP

void testWindowDefinitionTransfersSceneOwnershipToWindow();
void testWindowPropsSceneHandoffIsOneShotAcrossCopies();
void testWindowRetiresDetachedSceneAtFlushBoundary();
void testWindowDoesNotReclaimSceneDuringDetachNotification();

#endif // LOKA_SCENE_OWNERSHIP_TESTS_HPP
