#ifndef LOKA_SCENE_OWNERSHIP_TESTS_HPP
#define LOKA_SCENE_OWNERSHIP_TESTS_HPP

void testWindowDefinitionTransfersSceneOwnershipToWindow();
void testWindowPropsSceneHandoffIsOneShotAcrossCopies();
void testWindowRetiresDetachedSceneAtFlushBoundary();
void testWindowDefersSceneRetiredDuringDrainUntilNextFlush();
void testWindowDoesNotReclaimSceneDuringDetachNotification();
void testWindowReclaimDoesNotNotifySceneLifecycleObservers();
void testWindowReclaimFiresNoSceneCompositionCallbacks();
void testAppDefersWindowReclaimUntilInvalidationFlush();
void testAppDefersReentrantWindowCloseRequestUntilNextFlush();
void testAppReclaimsWindowCloseBatchInRequestOrder();
void testAppWindowReclaimDrainsRetiredScenesExactlyOnce();
void testAppWindowCloseRequestsAreIdempotent();
void testAppWindowClosedRejectsUndetachedOrActiveWindow();
void testAppDrainsPendingWindowClosuresAtDestruction();

#endif // LOKA_SCENE_OWNERSHIP_TESTS_HPP
