#ifndef LOKA_TESTS_SCENARIO_REEL_TESTS_HPP
#define LOKA_TESTS_SCENARIO_REEL_TESTS_HPP

void testScenarioReelPositionWrapsAndCountsCycles();
void testScenarioReelCellTablesMatchSharedRegistry();
void testScenarioSceneRearmRebuildsExampleStateFromDefinition();
void testScenarioReelRunsEveryMineSweeperCellEveryCycle();
void testScenarioReelRunsEveryHelloWorldCellEveryCycle();
void testScenarioReelCompositionRefusalIsTerminal();
void testScenarioLoopCompositionRefusalQuits();
void testSceneRearmRefusalPreservesNewerDetachRequest();
void testScenarioWindowDisplayTitlePreservesLogicalTitleAndDropsNativeObserver();
void testScenarioReelDriverAllocationRefusalRetiresInsteadOfWedging();
void testScenarioReelReplacementPreservesDriverAndStopsBeforeDetach();
void testStandaloneRunControlRearmsCompletedSceneWithoutQuittingApp();
void testStandaloneScenarioRailReplacementIsFailureAtomic();
void testStandaloneSceneRearmAllocationRefusalDoesNotCommitNextPass();

#endif // LOKA_TESTS_SCENARIO_REEL_TESTS_HPP
