#ifndef LOKA_TESTS_SCRAPBOOK_SCENARIO_TESTS_HPP
#define LOKA_TESTS_SCRAPBOOK_SCENARIO_TESTS_HPP

void testScrapbookRigLaunchRequiresConfigAndRefusesStandaloneTour();
void testScrapbookStandaloneTourAdvancesInOrderAndHoldsFinalScene();
void testScrapbookStandaloneMenuMatchesExample();
void testScrapbookStandaloneMountRefusalFailsClosed();
void testScenarioAuditFileWritesReadableRecords();

#endif // LOKA_TESTS_SCRAPBOOK_SCENARIO_TESTS_HPP
