#ifndef LOKA_TESTS_SMIRK_BENCH_TESTS_HPP
#define LOKA_TESTS_SMIRK_BENCH_TESTS_HPP

void testSmirkBenchNavModesResizeSeatsAndRetainSurface();
void testSmirkBenchNavModeDerivationAvoidsIdenticalWrites();
void testSmirkModelReflectsRefusesAndReclamps();

#endif // LOKA_TESTS_SMIRK_BENCH_TESTS_HPP
