#ifndef LOKA_TESTS_SMIRK_BENCH_TESTS_HPP
#define LOKA_TESTS_SMIRK_BENCH_TESTS_HPP

void testSmirkBenchOrientationFlipsAxesAndRetainsSurface();
void testSmirkBenchOrientationDerivationAvoidsIdenticalWrites();
void testSmirkBenchSurfaceExtentTracksContentSeat();
void testSmirkModelReflectsRefusesAndReclamps();

#endif // LOKA_TESTS_SMIRK_BENCH_TESTS_HPP
