#ifndef LOKA_TESTS_STACK_AXIS_RETENTION_TESTS_HPP
#define LOKA_TESTS_STACK_AXIS_RETENTION_TESTS_HPP

void testStackAxisFlipRetainsContainerAndChildAndRelayouts();
void testNestedRetainedAnonymousChildAppliesChangedPropsInBothModes();
void testNestedRetainedDepthThreeAppliesChangedPropsInBothModes();
void testNestedRetainedTaggedChildrenApplyChangedPropsInBothModes();
void testNestedChangedParentAndChildPropsApplyInBothModes();
void testNestedEquivalentDefinitionIsRepointedInBothModes();
void testNestedRetainedStructuralChildrenApplyInBothModes();
void testNestedMisplacedPolicyScopeReconcilesInBothModes();
void testNestedApplyRefusalFallsThroughToCurrentTreeInBothModes();
void testDeepEquivalentAnonymousSubtreesRetainNodesInBothModes();
void testDeepDifferentAnonymousSubtreeRebuildsLocallyInBothModes();
void testDeepEquivalentAnonymousSubtreeRepointsMetadataInBothModes();
void testControlPropsEquivalenceDistinguishesOwnedValuesAndBorrowedSources();

#endif // LOKA_TESTS_STACK_AXIS_RETENTION_TESTS_HPP
