#include "SurfaceGroundTests.hpp"
#include "app/style/SurfaceGround.hpp"
#include "support/TestVerify.hpp"

void testSurfaceGroundForEveryNodeKind()
{
  using namespace loka::app;
  using namespace loka::app::scene;
  LOKA_VERIFY(GroundForKind(NODE_KIND_CELL) == SURFACE_GROUND_CONTROL);
  LOKA_VERIFY(GroundForKind(NODE_KIND_RECT_SURFACE) == SURFACE_GROUND_DOCUMENT);
  LOKA_VERIFY(GroundForKind(NODE_KIND_BUTTON) == SURFACE_GROUND_NATIVE);
  LOKA_VERIFY(GroundForKind(NODE_KIND_EDIT_TEXT) == SURFACE_GROUND_NATIVE);
  LOKA_VERIFY(GroundForKind(NODE_KIND_POPUP_MENU) == SURFACE_GROUND_NATIVE);
  LOKA_VERIFY(GroundForKind(NODE_KIND_OPEN_FILE_DIALOG) == SURFACE_GROUND_NATIVE);
  LOKA_VERIFY(GroundForKind(NODE_KIND_SCROLL_BAR) == SURFACE_GROUND_NATIVE);
  LOKA_VERIFY(GroundForKind(NODE_KIND_TEXT_EDITOR) == SURFACE_GROUND_NATIVE);
  LOKA_VERIFY(GroundForKind(NODE_KIND_UNKNOWN) == SURFACE_GROUND_TRANSPARENT);
  LOKA_VERIFY(GroundForKind(NODE_KIND_BOX) == SURFACE_GROUND_TRANSPARENT);
  LOKA_VERIFY(GroundForKind(NODE_KIND_ZSTACK) == SURFACE_GROUND_TRANSPARENT);
  LOKA_VERIFY(GroundForKind(NODE_KIND_GRID) == SURFACE_GROUND_TRANSPARENT);
  LOKA_VERIFY(GroundForKind(NODE_KIND_STACK) == SURFACE_GROUND_TRANSPARENT);
  LOKA_VERIFY(GroundForKind(NODE_KIND_TEXT) == SURFACE_GROUND_TRANSPARENT);
  LOKA_VERIFY(GroundForKind(NODE_KIND_IMAGE_VIEW) == SURFACE_GROUND_TRANSPARENT);
  LOKA_VERIFY(GroundForKind(NODE_KIND_SCROLL_VIEW) == SURFACE_GROUND_TRANSPARENT);
  LOKA_VERIFY(GroundForKind(NODE_KIND_CANVAS) == SURFACE_GROUND_TRANSPARENT);
  LOKA_VERIFY(GroundForKind(NODE_KIND_ATTRIBUTED_TEXT) == SURFACE_GROUND_TRANSPARENT);
}
