#ifndef LOKA_TESTS_HPP
#define LOKA_TESTS_HPP

void testDependencyPropagationCases();
void testTrackerPropagation();
void testDeferredSideEffect();
void testTextInputOnChange();
void testBatchTransaction();
void testRAIITransaction();
void testDerivedStruct();
void testSceneManagerTransaction();
void testSceneManagerPendingTransactionsAndBindings();
void testSceneLifecyclePublishesDestroy();
void testNodeCompositionTree();
void testNodeCompositionShowIf();
void testSceneMountLifecycle();
void testSceneBoundaryNestedCompose();
void testStaticBoundaryPropagatesUpdateToDynamicChild();
void testDynamicBoundaryRecomposesOnlyOnChildDirty();
void testDynamicBoundaryPreservesChildIdentityUntilChildDirty();
void testDynamicBoundaryDetachesSubtreeBeforeChildRecompose();
void testDynamicBoundaryRecomposeDoesNotDuplicateBoundaryCallbacks();
void testBoundaryDirtyPolicyStaticImmediateDynamicDeferred();
void testDynamicBoundaryObservedParentOwnedStateTriggersChildRecompose();
void testPopupMenuSelectionStateDoesNotInvalidateScene();
void testOpenFileDialogStatesDoNotInvalidateScene();
void testSceneInvalidateUsesRequestedDirtyFlags();
void testSceneRequestInvalidateDefersUntilFlush();
void testSceneCompositionDiffMarksChildDirtyAsFullRebuild();
void testWindowFlushSceneInvalidationSynchronizesPendingPlatformWork();
void testStaticButtonAndCellTextAreOwnedPerDefinition();
void testMenuItemEnabledBoolDoesNotUseSharedStaticState();
void testConditionalNodeTeardownAfterOwnedStateIsSafe();
void testLokaCoreString();
void testLokaCoreCollections();
void testLokaDslStream();
void testStateBatchOverflow();
void testNestedTransaction();
void testNestedTransactionInvalidateTiming();

#endif // LOKA_TESTS_HPP
