#ifndef LOKA_TESTS_TEXT_EDITOR_HPP
#define LOKA_TESTS_TEXT_EDITOR_HPP
void testTextEditorActions();
void testTextEditorRefusals();
void testTextEditorHighlight();
void testTextEditorScene();
void testTextEditorReplace();
void testTextEditorReplaceRefusals();
void testTextEditorRequestTake();
void testTextEditorRequestIdle();
void testTextEditorRequestReposts();
void testTextEditorRequestRefusal();
void testTextEditorRequestBinding();
void testTextEditorRequestCancellationRepost();
void testTextEditorRequestSeatReplacement();
void testTextEditorRequestDetach();
void testTextEditorRequestCompletion();
void testTextEditorReportedStorage();
void testTextEditorSettlementReplies();
void testTextEditorSettlementLifetime();
void testTextEditorSettlementBinding();
void testTextEditorSettlementAdmission();
void testTextEditorSettlementSeam();
void testTextEditorSettlementTrace();
#endif
