#ifndef LOKA_TESTS_TOOLBOX_SCENE_PLATFORM_CONTRACT_TESTS_HPP
#define LOKA_TESTS_TOOLBOX_SCENE_PLATFORM_CONTRACT_TESTS_HPP

void testToolboxEnabledChangeUpdatesEveryMatchingControlKind();
void testToolboxPopupSelectionWriteUsesTrackerTransaction();

#endif // LOKA_TESTS_TOOLBOX_SCENE_PLATFORM_CONTRACT_TESTS_HPP
