#ifndef LOKA_TESTS_TOOLBOX_LAYOUT_CONTRACT_TESTS_HPP
#define LOKA_TESTS_TOOLBOX_LAYOUT_CONTRACT_TESTS_HPP

void testToolboxFixedBoxLayoutCommitsDeclaredExtent();
void testToolboxEmptyFixedBoxLayoutCommitsDeclaredExtent();
void testToolboxRowConsultsFixedChildWidth();
void testToolboxRowEmptyFragmentConsumesNoSeatOrGap();

#endif // LOKA_TESTS_TOOLBOX_LAYOUT_CONTRACT_TESTS_HPP
