#ifndef LOKA_TESTS_TURN_CLOCK_TESTS_HPP
#define LOKA_TESTS_TURN_CLOCK_TESTS_HPP
void testSceneFlushIsRefusedWhileClockSettles();
void testGuardWithoutClockKeepsSynchronousFlush();
void testGuardEnrollsEmptyTurnAndDefersFlush();
void testApplyTimeWriteSettlesAtCloseAndProjectsNextTurn();
void testCompletionTurnLeavesNoActiveClock();
void testInputInvocationInsideTurnDoesNotOpenClock();
#endif
