#ifndef LOKA_TESTS_TUTORIAL_SCENARIO_TESTS_HPP
#define LOKA_TESTS_TUTORIAL_SCENARIO_TESTS_HPP

void testTutorialIncrementSummaryToggleDrivesUiCommands();
void testTutorialIncrementSummaryToggleHoldsFinalSceneAndMatchesAudit();
void testTutorialStandaloneMenuUsesExampleDeclaration();
void testTutorialStandaloneFlowWritesExpectedAudit();
void testTutorialStandaloneMountRefusalFailsClosed();

#endif // LOKA_TESTS_TUTORIAL_SCENARIO_TESTS_HPP
