#ifndef LOKA_WIN32_SCENE_PLATFORM_TESTS_HPP
#define LOKA_WIN32_SCENE_PLATFORM_TESTS_HPP

void testWin32ScenePlatformRelayoutReusesControlContexts();
void testWin32ScenePlatformRelayoutReusesCellAndTextContexts();
void testWin32ScenePlatformDynamicPropsAndLayoutReuseContexts();
void testWin32ScenePlatformFullRebuildFlagControlsContextReuse();
void testWin32ScenePlatformChildRebuildCleansUpOldContexts();

#endif // LOKA_WIN32_SCENE_PLATFORM_TESTS_HPP
