#ifndef LOKA_WIN32_SCENE_PLATFORM_TESTS_HPP
#define LOKA_WIN32_SCENE_PLATFORM_TESTS_HPP

void testWin32ScenePlatformRelayoutReusesControlContexts();
void testWin32ScenePlatformRelayoutReusesCellAndTextContexts();

#endif // LOKA_WIN32_SCENE_PLATFORM_TESTS_HPP
