#ifndef LOKA_WIN32_SCENE_PLATFORM_TESTS_HPP
#define LOKA_WIN32_SCENE_PLATFORM_TESTS_HPP

void testWin32ScenePlatformRelayoutReusesControlContexts();
void testWin32ScenePlatformRelayoutReusesCellAndTextContexts();
void testWin32ScenePlatformDynamicPropsAndLayoutReuseContexts();
void testWin32ScenePlatformFullRebuildFlagControlsContextReuse();
void testWin32ScenePlatformChildRebuildCleansUpOldContexts();
void testWin32ScenePlatformForeignObservedChildRebuildSwapsContexts();
void testWin32ScenePlatformForeignObservedChildRebuildPreservesSiblingContexts();
void testWin32ScenePlatformForeignObservedChildReorderPreservesSiblingContexts();
void testWin32ScenePlatformBoundaryLocalPaintQueuesDirtyRect();
void testWin32ScenePlatformPaintOnlyStateChangeUsesLocalApplyPath();
void testWin32ScenePlatformPropsOnlyOnChangeSkipsLayout();

#endif // LOKA_WIN32_SCENE_PLATFORM_TESTS_HPP
