#ifndef LOKA_WIN32_RECT_SURFACE_PAINT_TESTS_HPP
#define LOKA_WIN32_RECT_SURFACE_PAINT_TESTS_HPP

void testWin32RectSurfacePaintQueuesBoundedParentSubtree();
void testWin32RectSurfaceImagePaintsDdbOpaque();
void testWin32RectSurfaceImageKeepsBinaryAlphaPath();

#endif
