#ifndef LOKA_WIN32_MENU_ATTACHMENT_TESTS_HPP
#define LOKA_WIN32_MENU_ATTACHMENT_TESTS_HPP

void testWin32MenuAttachmentProjectsOnceForEqualBar();
void testWin32MenuAttachmentReleaseFromSourceDisconnects();
void testWin32SceneDetachReleasesMenu();
void testWin32TwoWindowsOwnTheirMenus();
void testWin32AppShutdownReleasesMenuBeforeAttachmentDestruction();

void testWin32MenuAcceleratorTranslatesDeclaredShortcut();
void testWin32QuitHasNoDefaultAccelerator();
void testWin32MenuAcceleratorInertAfterRelease();
void testWin32MenuAcceleratorSwapsWithProjection();
void testWin32TwoWindowsOwnTheirAccelerators();
void testWin32MenuAcceleratorPrecedesDialogAndDispatch();
void testWin32MenuTitleFollowsState();
void testWin32MenuPopupTitleFollowsState();
void testWin32MenuTitleStateUnbindsOnRelease();
#endif
