#ifndef LOKA_WINDOW_FRAME_STATE_TESTS_HPP
#define LOKA_WINDOW_FRAME_STATE_TESTS_HPP

void testWindowFrameStateDrivesDerivedState();
void testWindowNativeFrameDrivesDerivedStateWithoutEchoingIntent();

#endif // LOKA_WINDOW_FRAME_STATE_TESTS_HPP
