#ifndef LOKA_WRITE_SEAT_TESTS_HPP
#define LOKA_WRITE_SEAT_TESTS_HPP
void testWriteSeatSettlesIdleOwnerTracker();
void testWriteSeatJoinsOpenTracker();
void testWriteSeatRawAndInvalid();
void testWriteSeatPropsIdentity();
void testNullInputDoorLifetime();
void testSeatInsideTurnEnrollsOwnerAndSettlesAtTail();
void testSeatOutsideClockKeepsLegacyTransaction();
void testSeatUnderLegacyGuardWritesOnly();
void testSeatFirstNestedGuardCommitsAtTail();
void testSeatDuringCleanupWritesWithoutRoute();
void testSeatAfterRefusedSettleKeepsLegacyTransaction();
void testSeatAbstractTrackerKeepsLegacyTransaction();
void testTwoSeatsOneHandlerProjectOnce();
void testTwoSeatsWithoutClockProjectTwice();
void testThreeSeatOwnersTwoScenesSeeEveryCommit();
void testSeatOwnerDestroyedDuringApplyLeavesClock();
void testFlowStepSeatGuardOrders();
void testGuardInsideTurnJoinsAndSettlesAtTail();
void testGuardOutsideClockKeepsLegacyBracket();
void testGuardOnBusyLedgerNestsLegacyLevel();
void testGuardCallbackFiresOnlyOutsideTurn();
void testStandaloneGuardCommitsBeforeReadInsideTurn();
void testGuardedBlocksProjectOnceAtTail();
void testMenuCompositionCommitsBeforeReadInsideTurn();
void testBootstrapVisibilityCommitsBeforeReadInsideTurn();
void testFlowOnSuccessJoinsTurn();
#endif
