// Generated by tools/ci/gen_style_vocab.py. Do not edit.
export type FontSize = 9 | 10 | 12 | 14 | 18 | 24;
export type TextWeight = "normal" | "bold";
export type TextWrap = 0 | 1 | 2;
export type TextTruncation = 0 | 1 | 2;
export type TextAlign = 0 | 1 | 2;

export interface TextStyle {
  /** Any integer; snapped at declaration to the nearest FontSize, ties down. */
  size?: number;
  weight?: TextWeight;
  italic?: boolean;
}

export interface BlockStyle {
  wrap?: TextWrap;
  truncation?: TextTruncation;
  align?: TextAlign;
}

/**
 * JS globals (signatures only; node globals are not declared in this file):
 * Text(value: string | Seat, style?: TextStyle)
 * Markup(markup: string, style?: TextStyle)
 */
