// Generated by tools/ci/gen_style_vocab.py. Do not edit.
export type FontSize = 9 | 10 | 12 | 14 | 18 | 24;
export type TextWeight = 0 | 1;
export type TextWrap = 0 | 1 | 2;
export type TextTruncation = 0 | 1 | 2;

export interface TextStyle {
  fontSize?: FontSize;
  weight?: TextWeight;
  italic?: boolean;
}

export interface BlockStyle {
  wrap?: TextWrap;
  truncation?: TextTruncation;
}
