// Generated by tools/ci/gen_style_vocab.py. Do not edit.
#ifndef LOKA_APP_STYLE_STYLE_VOCAB_ENUMS_HPP
#define LOKA_APP_STYLE_STYLE_VOCAB_ENUMS_HPP

namespace loka
{
  namespace app
  {
    enum TextWeight
    {
      TEXT_WEIGHT_NORMAL = 0,
      TEXT_WEIGHT_BOLD = 1
    };

    enum TextWrap
    {
      TEXT_WRAP_NONE = 0,
      TEXT_WRAP_WORD = 1,
      TEXT_WRAP_CHAR = 2
    };

    enum TextTruncation
    {
      TEXT_TRUNCATION_NONE = 0,
      TEXT_TRUNCATION_CLIP = 1,
      TEXT_TRUNCATION_ELLIPSIS = 2
    };

    enum TextAlign
    {
      TEXT_ALIGN_LEFT = 0,
      TEXT_ALIGN_CENTER = 1,
      TEXT_ALIGN_RIGHT = 2
    };

    template <int N> struct FontSize;
    namespace detail
    {
      enum { kStyleVocabularySizeCount = 6 };
      extern const int StyleVocabularySizes[];
      extern const int StyleVocabularySizeCount;
    }
  } // namespace app
} // namespace loka

#endif // LOKA_APP_STYLE_STYLE_VOCAB_ENUMS_HPP

#if defined(LOKA_STYLE_VOCAB_DEFINE_SIZES) && !defined(LOKA_APP_STYLE_STYLE_VOCAB_SIZES_HPP)
#define LOKA_APP_STYLE_STYLE_VOCAB_SIZES_HPP

namespace loka
{
  namespace app
  {
    template <> struct FontSize<9> : public TextStyle
    {
      FontSize() : TextStyle()
      {
        this->fontSize_ = 9;
        this->hasFontSize_ = true;
      }
    };

    template <> struct FontSize<10> : public TextStyle
    {
      FontSize() : TextStyle()
      {
        this->fontSize_ = 10;
        this->hasFontSize_ = true;
      }
    };

    template <> struct FontSize<12> : public TextStyle
    {
      FontSize() : TextStyle()
      {
        this->fontSize_ = 12;
        this->hasFontSize_ = true;
      }
    };

    template <> struct FontSize<14> : public TextStyle
    {
      FontSize() : TextStyle()
      {
        this->fontSize_ = 14;
        this->hasFontSize_ = true;
      }
    };

    template <> struct FontSize<18> : public TextStyle
    {
      FontSize() : TextStyle()
      {
        this->fontSize_ = 18;
        this->hasFontSize_ = true;
      }
    };

    template <> struct FontSize<24> : public TextStyle
    {
      FontSize() : TextStyle()
      {
        this->fontSize_ = 24;
        this->hasFontSize_ = true;
      }
    };

  } // namespace app
} // namespace loka

#endif // generated size specialisations

#if defined(LOKA_STYLE_VOCAB_DEFINE_STORAGE) && !defined(LOKA_APP_STYLE_STYLE_VOCAB_STORAGE_HPP)
#define LOKA_APP_STYLE_STYLE_VOCAB_STORAGE_HPP

namespace loka
{
  namespace app
  {
    namespace detail
    {
      const int StyleVocabularySizes[] = {9, 10, 12, 14, 18, 24};
      const int StyleVocabularySizeCount =
          static_cast<int>(sizeof(StyleVocabularySizes) / sizeof(StyleVocabularySizes[0]));
    }
  } // namespace app
} // namespace loka

#endif // generated vocabulary storage
