// Generated by lrpc. Edit the manifest, not this file.
#ifndef LOKA_LRPC_GENERATED_R_HPP
#define LOKA_LRPC_GENERATED_R_HPP

#include <cstddef>

#include "core/resource/lrpk/LrpkFormat.hpp"

namespace R
{
  typedef loka::core::resource::lrpk::U32 AssetId;
  typedef std::size_t BagIndex;
  typedef loka::core::resource::lrpk::AssetKind AssetKind;

  /** One baked resource identity. All fields come from the same
      manifest record that lrpc wrote into ASSETS.LRP. */
  struct AssetRef
  {
    AssetId id;
    BagIndex bag;
    AssetKind kind;
  };

  const AssetId IdSpaceStamp = 1993003961UL;
  const std::size_t AssetCount = 6;
  const std::size_t BagCount = 6;

  namespace Pages
  {
    const AssetRef Page1 = {1001UL, 1, loka::core::resource::lrpk::ASSET_KIND_IMAGE};
    const AssetRef Page2 = {1002UL, 2, loka::core::resource::lrpk::ASSET_KIND_IMAGE};
    const AssetRef Page3 = {1003UL, 3, loka::core::resource::lrpk::ASSET_KIND_IMAGE};
    const AssetRef Page4 = {1004UL, 4, loka::core::resource::lrpk::ASSET_KIND_IMAGE};
    const AssetRef Page5 = {1005UL, 5, loka::core::resource::lrpk::ASSET_KIND_STRING};

    const AssetRef Assets[] = {
      {1001UL, 1, loka::core::resource::lrpk::ASSET_KIND_IMAGE},
      {1002UL, 2, loka::core::resource::lrpk::ASSET_KIND_IMAGE},
      {1003UL, 3, loka::core::resource::lrpk::ASSET_KIND_IMAGE},
      {1004UL, 4, loka::core::resource::lrpk::ASSET_KIND_IMAGE},
      {1005UL, 5, loka::core::resource::lrpk::ASSET_KIND_STRING}
    };
    const std::size_t AssetCount = 5;
  } // namespace Pages

  namespace UI
  {
    const AssetRef RefusedBadge = {9001UL, 0, loka::core::resource::lrpk::ASSET_KIND_IMAGE};

    const AssetRef Assets[] = {
      {9001UL, 0, loka::core::resource::lrpk::ASSET_KIND_IMAGE}
    };
    const std::size_t AssetCount = 1;
  } // namespace UI

} // namespace R

#endif // LOKA_LRPC_GENERATED_R_HPP
