if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
  message(FATAL_ERROR "INPUT and OUTPUT are required")
endif()

file(READ "${INPUT}" main_js)
string(REPLACE "\\" "\\\\" main_js "${main_js}")
string(REPLACE "\"" "\\\"" main_js "${main_js}")
string(REPLACE "\n" "\\n\"\n\"" main_js "${main_js}")
get_filename_component(input_name "${INPUT}" NAME)
file(WRITE "${OUTPUT}" "// Generated from ${input_name}; do not edit.\nreturn \"${main_js}\";\n")
