#!/usr/bin/env python3
"""Generate the shared C++, TypeScript, and JavaScript style vocabulary."""

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]


def enum_lines(name, prefix, entries):
    lines = ["    enum %s" % name, "    {"]
    items = list(entries.items())
    for index, (key, value) in enumerate(items):
        comma = "," if index + 1 < len(items) else ""
        lines.append("      %s_%s = %d%s" % (prefix, key, value, comma))
    lines.extend(["    };", ""])
    return lines


def generate_cpp(vocab):
    lines = [
        "// Generated by tools/ci/gen_style_vocab.py. Do not edit.",
        "#ifndef LOKA_APP_STYLE_STYLE_VOCAB_ENUMS_HPP",
        "#define LOKA_APP_STYLE_STYLE_VOCAB_ENUMS_HPP",
        "",
        "namespace loka",
        "{",
        "  namespace app",
        "  {",
    ]
    lines += enum_lines("TextWeight", "TEXT_WEIGHT", vocab["weights"])
    lines += enum_lines("TextWrap", "TEXT_WRAP", vocab["wrap"])
    lines += enum_lines("TextTruncation", "TEXT_TRUNCATION", vocab["truncation"])
    sizes = ", ".join(str(value) for value in vocab["sizes"])
    lines += [
        "    template <int N> struct FontSize;",
        "    namespace detail",
        "    {",
        "      enum { kStyleVocabularySizeCount = %d };" % len(vocab["sizes"]),
        "      extern const int StyleVocabularySizes[];",
        "      extern const int StyleVocabularySizeCount;",
        "    }",
        "  } // namespace app",
        "} // namespace loka",
        "",
        "#endif // LOKA_APP_STYLE_STYLE_VOCAB_ENUMS_HPP",
        "",
        "#if defined(LOKA_STYLE_VOCAB_DEFINE_SIZES) && !defined(LOKA_APP_STYLE_STYLE_VOCAB_SIZES_HPP)",
        "#define LOKA_APP_STYLE_STYLE_VOCAB_SIZES_HPP",
        "",
        "namespace loka",
        "{",
        "  namespace app",
        "  {",
    ]
    for size in vocab["sizes"]:
        lines += [
            "    template <> struct FontSize<%d> : public TextStyle" % size,
            "    {",
            "      FontSize() : TextStyle()",
            "      {",
            "        this->fontSize_ = %d;" % size,
            "        this->hasFontSize_ = true;",
            "      }",
            "    };",
            "",
        ]
    lines += [
        "  } // namespace app",
        "} // namespace loka",
        "",
        "#endif // generated size specialisations",
        "",
        "#if defined(LOKA_STYLE_VOCAB_DEFINE_STORAGE) && !defined(LOKA_APP_STYLE_STYLE_VOCAB_STORAGE_HPP)",
        "#define LOKA_APP_STYLE_STYLE_VOCAB_STORAGE_HPP",
        "",
        "namespace loka",
        "{",
        "  namespace app",
        "  {",
        "    namespace detail",
        "    {",
        "      const int StyleVocabularySizes[] = {%s};" % sizes,
        "      const int StyleVocabularySizeCount =",
        "          static_cast<int>(sizeof(StyleVocabularySizes) / sizeof(StyleVocabularySizes[0]));",
        "    }",
        "  } // namespace app",
        "} // namespace loka",
        "",
        "#endif // generated vocabulary storage",
        "",
    ]
    return "\n".join(lines)


def ts_type(value):
    return {"fontSize": "FontSize", "weight": "TextWeight", "italic": "boolean",
            "wrap": "TextWrap", "truncation": "TextTruncation"}[value]


def union(values):
    return " | ".join(str(value) for value in values)


def generate_typescript(vocab):
    lines = [
        "// Generated by tools/ci/gen_style_vocab.py. Do not edit.",
        "export type FontSize = %s;" % union(vocab["sizes"]),
        "export type TextWeight = %s;" % union(json.dumps(key.lower()) for key in vocab["weights"]),
        "export type TextWrap = %s;" % union(vocab["wrap"].values()),
        "export type TextTruncation = %s;" % union(vocab["truncation"].values()),
        "",
    ]
    for interface in ("TextStyle", "BlockStyle"):
        lines.append("export interface %s {" % interface)
        for field in vocab["fields"][interface]:
            if interface == "TextStyle" and field == "fontSize":
                # The JS door accepts any integer and snaps it to the nearest
                # vocabulary size (ties down), so the type is number, not the union.
                lines.append("  /** Any integer; snapped at declaration to the nearest FontSize, ties down. */")
                lines.append("  size?: number;")
                continue
            lines.append("  %s?: %s;" % (field, ts_type(field)))
        lines.extend(["}", ""])
    lines += [
        "/**",
        " * JS globals (signatures only; node globals are not declared in this file):",
        " * Text(value: string | Seat, style?: TextStyle)",
        " * Markup(markup: string, style?: TextStyle)",
        " */",
        "",
    ]
    return "\n".join(lines)


def generate_runtime(vocab):
    sizes = ",".join(str(value) for value in vocab["sizes"])
    return "// Generated by tools/ci/gen_style_vocab.py. Do not edit.\nmodule.exports = {sizes:[%s]};\n" % sizes


def write(root, relative, content):
    path = root / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-root", type=Path, default=ROOT)
    parser.add_argument("--vocab", type=Path, default=ROOT / "tools/style-vocab.json")
    args = parser.parse_args()
    vocab = json.loads(args.vocab.read_text(encoding="utf-8"))
    write(args.output_root, Path("common/app/style/StyleVocab.hpp"), generate_cpp(vocab))
    write(args.output_root, Path("docs/smirkycard/loka-style.d.ts"), generate_typescript(vocab))
    write(args.output_root, Path("tools/style-vocab.runtime.js"), generate_runtime(vocab))


if __name__ == "__main__":
    main()
